name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          set -euxo pipefail
          npm ci

      - name: Build
        run: |
          set -euxo pipefail
          npm run build

      - name: Adjust paths for GitHub Pages
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          sed -i "s,href=\"style.css\",href=\"/$REPO_NAME/style.css\",g" dist/index.html
          sed -i "s,src=\"app.js\",src=\"/$REPO_NAME/app.js\",g" dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"
