name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Use npm ci for reliable installs (if lockfile is up-to-date)
      - name: Install deps
        run: |
          set -euxo pipefail
          npm ci

      - name: Build
        run: npm run build

      # Fix asset paths for GitHub Pages; skip if files are missing
      - name: Rewrite paths for Pages
        run: |
          set -euxo pipefail
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          if [ -f dist/index.html ]; then
            sed -i "s,href=\"style.css\",href=\"/$REPO_NAME/style.css\",g" dist/index.html
            sed -i "s,src=\"app.js\",src=\"/$REPO_NAME/app.js\",g" dist/index.html
          else
            echo "dist/index.html not found; skipping"
          fi
          if [ -f dist/service-worker.js ]; then
            sed -i "s,{{REPO_NAME}},$REPO_NAME,g" dist/service-worker.js
          else
            echo "No dist/service-worker.js; skipping rewrite"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
